AntChainOpenLabs/Smart-Intermediate-Representation

smart_ir/src/ir/intrinsic_func.rs, smart_ir/src/ir_codegen/intrinsic/mod.rs
- [ x ] N
- [ x ] Other
- [ x ] N
- [ x ] Manual test (add detailed scripts or steps below)
```release-note
None
```
=> support ir.builtin.co_call in ir

README.md, doc/Contributing Guide.md
=> chore: update doc

doc/specification/SmartIR.md
=> doc: add ir spec

README.md, doc/specification/SmartIR.md, docker/ir-cli-builder/README.md, smart_ir/src/ir/cfg.rs
The doc in README.md
```release-note
None
```
=> doc: add document for the IR Specification in README.md

.github/workflows/release.yml, README.md
=> chore: fix release ci, set docker file path

docker/ir-cli/Dockerfile
=> chore: fix release

docker/ir-cli-builder/Dockerfile
=> chore: update CI

smart_ir/src/ir/cfg.rs, yul_to_ir/Cargo.lock, yul_to_ir/Cargo.toml, yul_to_ir/build.rs, yul_to_ir/src/ast.rs, yul_to_ir/src/context.rs, yul_to_ir/src/instruction.rs, yul_to_ir/src/lib.rs, yul_to_ir/src/test.rs, yul_to_ir/src/transform.rs, yul_to_ir/src/yul.lalrpop
=> feat: support transform ERC20 by yul to smart_ir

smart_ir/src/ir/frontend/ir.lalrpop, smart_ir/src/ir/frontend/mod.rs, smart_ir/src/ir/frontend/translate.rs
=> fix: parse ret and  declaration correctly

smart_ir/src/ir_codegen/intrinsic/map.rs, smart_ir/src/ir_codegen/intrinsic/vector.rs, smart_ir/src/runtime/stdlib/qhashtbl.c, smart_ir/src/runtime/stdlib/qvector.c
=> fix: add iter type used marker

smart_ir/src/ir/frontend/ir.lalrpop
=> fix: parse single expr correctly

ir_cli/src/tests/e2e/as.rs, ir_cli/src/tests/e2e/assign.rs, ir_cli/src/tests/e2e/bigint.rs, ir_cli/src/tests/e2e/break.rs, ir_cli/src/tests/e2e/builtin.rs, ir_cli/src/tests/e2e/calculation.rs, ir_cli/src/tests/e2e/call.rs, ir_cli/src/tests/e2e/continue.rs, ir_cli/src/tests/e2e/declaration.rs, ir_cli/src/tests/e2e/for.rs, ir_cli/src/tests/e2e/func.rs, ir_cli/src/tests/e2e/if.rs, ir_cli/src/tests/e2e/json.rs, ir_cli/src/tests/e2e/map.rs, ir_cli/src/tests/e2e/math.rs, ir_cli/src/tests/e2e/mod.rs, ir_cli/src/tests/e2e/parampack.rs, ir_cli/src/tests/e2e/select.rs, ir_cli/src/tests/e2e/ssz.rs, ir_cli/src/tests/e2e/str.rs, ir_cli/src/tests/e2e/vec.rs, ir_cli/src/tests/examples/mod.rs, ir_cli/src/tests/mod.rs, ir_cli/src/vm/mod.rs, smart_ir/src/ir/frontend/translate.rs, smart_ir/src/ir_codegen/ty.rs, smart_ir/src/runtime/stdlib/qhashtbl.h, smart_ir/src/runtime/stdlib/storage_t.c, smart_ir/src/runtime/stdlib/storage_t.h
=> update: e2e tests

ir_cli/src/tests/e2e/continue.rs, smart_ir/src/ir/cfg.rs, smart_ir/src/ir/context.rs, smart_ir/src/ir/intrinsic_func.rs, smart_ir/src/ir/printer.rs, smart_ir/src/ir_codegen/ir.rs, smart_ir/src/ir_codegen/ty.rs, yul_to_ir/src/test.rs, yul_to_ir/src/transform.rs
=> feature: ir spec supports tuple type of func call ret

smart_ir/src/ir/cfg.rs, yul_to_ir/Cargo.lock, yul_to_ir/src/ast.rs, yul_to_ir/src/context.rs, yul_to_ir/src/test.rs, yul_to_ir/src/transform.rs
=> feature: support tuple type

docker/ir-cli/Dockerfile
=> update: release ci

ir_cli/README.md
=> doc: ai intent readme

ir_cli/src/tests/e2e/match.rs, ir_cli/src/tests/e2e/mod.rs, smart_ir/src/ir_codegen/ir.rs, yul_to_ir/src/test.rs, yul_to_ir/src/transform.rs
=> add sir match instr codegen and yul2sir switch2match

smart_ir/src/runtime/stdlib/stdlib.c, smart_ir/src/runtime/stdlib/stdlib.h, smart_ir/src/runtime/stdlib/test/CMakeLists.txt, smart_ir/src/runtime/stdlib/test/run_test.sh
=> fix: fix runtime c test

yul_to_ir/src/test.rs, yul_to_ir/src/transform.rs
=> feat: yul continue and break stmt to sir

ir_cli/Cargo.lock, smart_ir/Cargo.lock, smart_ir/Cargo.toml, smart_ir_macro/Cargo.toml
=> chore: update cargo.toml

README.md
=> chore: remove wx QR code
